### ISSUE TITLE
gulp serve:dist not working

### ISSUE THREAD

**Issue by andreasonny83** [FountainJS/generator-fountain-webapp#28]
Installing the generator with:
- Anugular 1
- None with Bower and script injection
- ES2015 today with Babel
- SASS
- A working landing page

when running `gulp serve:dist`, all I can see is the `Loading...` message and no JS  errors.
The template file seems correctly generated and also all the other minified files. I can't figure out what is missing.

**Comment by andreasonny83** [comment]
I discovered the issue is related to the `generator-fountain-gulp` but, because that generator is shared across `generator-fountain-angular1`, `generator-fountain-angular2` and `generator-fountain-react` and I'm not sure the problem is also present in the other 2 generators, I can only share how I fixed the grunt task on my `generator-fountain-angular1`.
In the `gulp_tasks/build.js` I removed the following lines of code:

```
  11: - const inject = require('gulp-inject');

  19: - const partialsInjectFile = gulp.src(conf.path.tmp('templateCacheHtml.js'), {read: false});
  20: - const partialsInjectOptions = {
  21: - starttag: '<!-- inject:partials -->',
  22: - ignorePath: conf.paths.tmp,
  23: - addRootSlash: false
  24: - };
  25: -

  31: -  .pipe(inject(partialsInjectFile, partialsInjectOptions))
```

and in `src/index.html`

```
37: -  <!-- inject:partials -->
38: -  <!-- angular templates will be automatically converted in js and inserted here -->
39: -  <!-- endinject -->
```

**Comment by micaelmbagira** [comment]
It's fixed on master, it will be on next release, probably this week.

**Comment by Swiip** [comment]
released

**Comment by andreaceccanti** [comment]
I still get this error with 1.0.0-rc1, generating an angular2 webapp with Typescript and systemjs
